from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signupWindow(object):
    def setupUi(self, signupWindow):
        signupWindow.setObjectName("signupWindow")
        signupWindow.resize(347, 645)
        self.centralwidget = QtWidgets.QWidget(signupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 321, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout.addWidget(self.textEdit_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.textEdit_6 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout.addWidget(self.textEdit_6)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit_5 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout.addWidget(self.textEdit_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        signupWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signupWindow)
        self.statusbar.setObjectName("statusbar")
        signupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(signupWindow)
        QtCore.QMetaObject.connectSlotsByName(signupWindow)

    def retranslateUi(self, signupWindow):
        _translate = QtCore.QCoreApplication.translate
        signupWindow.setWindowTitle(_translate("signupWindow", "signupWindow"))
        self.label.setText(_translate("signupWindow", "name"))
        self.label_2.setText(_translate("signupWindow", "phones"))
        self.label_3.setText(_translate("signupWindow", "password"))
        self.label_5.setText(_translate("signupWindow", "marital status"))
        self.label_4.setText(_translate("signupWindow", "username"))
        self.label_6.setText(_translate("signupWindow", "NationalCode"))
        self.pushButton.setText(_translate("signupWindow", "save"))
