# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui_mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tasks_sort_by_tags = QtWidgets.QPushButton(self.centralwidget)
        self.tasks_sort_by_tags.setObjectName("tasks_sort_by_tags")
        self.gridLayout.addWidget(self.tasks_sort_by_tags, 1, 0, 1, 2)
        self.edit_task = QtWidgets.QPushButton(self.centralwidget)
        self.edit_task.setObjectName("edit_task")
        self.gridLayout.addWidget(self.edit_task, 0, 1, 1, 1)
        self.new_task = QtWidgets.QPushButton(self.centralwidget)
        self.new_task.setObjectName("new_task")
        self.gridLayout.addWidget(self.new_task, 0, 0, 1, 1)
        self.tags_list = QtWidgets.QPushButton(self.centralwidget)
        self.tags_list.setObjectName("tags_list")
        self.gridLayout.addWidget(self.tags_list, 1, 4, 1, 1)
        self.tasks_list = QtWidgets.QPushButton(self.centralwidget)
        self.tasks_list.setObjectName("tasks_list")
        self.gridLayout.addWidget(self.tasks_list, 0, 2, 1, 1)
        self.sort = QtWidgets.QPushButton(self.centralwidget)
        self.sort.setObjectName("sort")
        self.gridLayout.addWidget(self.sort, 0, 4, 1, 1)
        self.group = QtWidgets.QPushButton(self.centralwidget)
        self.group.setObjectName("group")
        self.gridLayout.addWidget(self.group, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_6.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Hello</span></p></body></html>"))
        self.tasks_sort_by_tags.setText(_translate("MainWindow", "tasks sort by tags"))
        self.edit_task.setText(_translate("MainWindow", "edit task"))
        self.new_task.setText(_translate("MainWindow", "new task"))
        self.tags_list.setText(_translate("MainWindow", "tags list"))
        self.tasks_list.setText(_translate("MainWindow", "tasks list"))
        self.sort.setText(_translate("MainWindow", "sort"))
        self.group.setText(_translate("MainWindow", "group"))
        self.exit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
