# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_singup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class singup(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.singupl = QtWidgets.QLabel(self.centralwidget)
        self.singupl.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(36)
        self.singupl.setFont(font)
        self.singupl.setObjectName("singupl")
        self.verticalLayout.addWidget(self.singupl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setObjectName("username")
        self.phonenumber = QtWidgets.QLineEdit(self.centralwidget)
        self.phonenumber.setObjectName("phonenumber")
        self.gridLayout.addWidget(self.phonenumber, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.username, 0, 0, 1, 1)
        self.pass1 = QtWidgets.QLineEdit(self.centralwidget)
        self.pass1.setObjectName("pass1")
        self.gridLayout.addWidget(self.pass1, 1, 0, 1, 1)
        self.pass2 = QtWidgets.QLineEdit(self.centralwidget)
        self.pass2.setObjectName("pass2")
        self.gridLayout.addWidget(self.pass2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setObjectName("status")
        self.horizontalLayout_8.addWidget(self.status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.SingUp = QtWidgets.QPushButton(self.centralwidget)
        self.SingUp.setObjectName("SingUp")
        self.horizontalLayout_8.addWidget(self.SingUp)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setObjectName("back")
        self.horizontalLayout_8.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_8.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.singupl.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sing up</p></body></html>"))
        self.pass2.setPlaceholderText(_translate("MainWindow", "password"))
        self.pass1.setPlaceholderText(_translate("MainWindow", "password"))
        self.phonenumber.setPlaceholderText(_translate("MainWindow", "phone number"))
        self.username.setPlaceholderText(_translate("MainWindow", "user name"))
        self.status.setText(_translate("MainWindow", ""))
        self.SingUp.setText(_translate("MainWindow", "Sing Up"))
        self.back.setText(_translate("MainWindow", "back"))
        self.exit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = singup()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
