# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui_task_by_tag.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tsbt(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(48)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.Status = QtWidgets.QLabel(self.centralwidget)
        self.Status.setObjectName("Status")
        self.horizontalLayout_9.addWidget(self.Status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setObjectName("back")
        self.horizontalLayout_9.addWidget(self.back)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_9.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Task list</p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "tag"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "ID"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "title"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "detail"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "date created"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "last edited"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "deadline"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "tags"))
        self.treeWidget.headerItem().setText(8, _translate("MainWindow", "creator"))
        self.treeWidget.headerItem().setText(9, _translate("MainWindow", "Done?"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.Status.setText(_translate("MainWindow", ""))
        self.back.setText(_translate("MainWindow", "back"))
        self.exit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = tsbt()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
